### PR TITLE
Changed item tooltip rendering to widget tooltip rendering(Spout)

### PR DESCRIPTION
**Pull request by masp**
This allows for line breaks which is why I did it, but it also allows for greater standardization if changes are made to the method.

### CODE REVIEW

**Comment by Afforess** [comment]
Could you make sure the //Spout tags start at the beginning of your changes, and squash this into 1 commit.

**Comment by masp** [comment]
Okay, sorry, I'm a bit new to this Github operations. I was curious as to whether I put the //Spout start and //Spout end before comments.

**Comment by narrowtux** [comment]
I request you to delete your repository immediately because it contains the complete decompiled minecraft source.

**Comment by masp** [comment]
Deleted

**Pull request closed without merging**
