### PR TITLE
Fixed creative inventory.

### PR DESCRIPTION
**Pull request by Wolftein**
Signed-off-by: Wolftein agustin.l.alvarez@hotmail.com

### CODE REVIEW

**Comment by stephenwilliams** [comment]
Is there any difference between the clean decompiled and this?

**Comment by Wolftein** [comment]
Line 468 is just a quick fix, i know there is a better way because i just make always to use slider

**Comment by stephenwilliams** [comment]
Any changes need to be marked

For single line change put the following at the end of the line
`// Spout - short description of change`

For blocks of changes put the following on the line before the block
`// Spout start - short description of change`
and at the end of the block
`// Spout end`

**Comment by Wolftein** [comment]
Sorry Alta, i forgot doing that

**Comment by stephenwilliams** [comment]
Its all good, just have to be picky about it because it can get lost in an update if it isn't marked

**Comment by Wolftein** [comment]
Done ^^

**Comment by stephenwilliams** [comment]
Alright, I'll try to get this tested either tonight or tomorrow morning and pull it after I have. 

Thanks :)

**Comment by ZNickq** [comment]
Are you sure that was the issue Wolftein? The error is NoSuchFieldError, from testing it seems like the itemRenderer name isn't re-obfuscated properly...

**Comment by Wolftein** [comment]
Delete this pull request, zNickq was right i dunno why i was getting the error there

**Pull request closed without merging**
