### PR TITLE
updated to 1.4.5

### PR DESCRIPTION
**Pull request by hapm**
Signed off version

### CODE REVIEW

**Comment by Zidane** [comment]
Did you fix the exception I gave you in the last commit's messages @HAPM ?

**Comment by hapm** [comment]
Did only sign off what i had so far.

**Comment by Zidane** [comment]
No problem we got it fixed.

Thanks a LOT.

**Comment by hapm** [comment]
Looks like this is closed then?

**Comment by Zidane** [comment]
Indeed :P.

Thanks again @HAPM.

**Pull request closed without merging**
