### PR TITLE
Screenevents

### PR DESCRIPTION
**Pull request by Killili**
Send ScreenOpen and ScreenClose events for every screen.
And cancel them if needed.

### CODE REVIEW

**Comment by Afforess** [comment]
One suggestion. In GuiScreen, There is the massive switch for finding the screen type from the instance (https://github.com/SpoutDev/Spoutcraft/blob/master/src/minecraft/net/minecraft/src/GuiScreen.java#L110), that could be replaced with ScreenType.getType(this).

**Comment by Killili** [comment]
i did that .... it has been lost in some git troubles i had will add that in a sec

**Comment by Afforess** [comment]
Okay, looks better. Has it actually been testing in game?

**Comment by Killili** [comment]
Yes ofcourse, actually i had a long discussion on #spoutdev about the commit strategy and why it is bad to commit untested code to master ;)

**Comment by Afforess** [comment]
> Yes ofcourse, actually i had a long discussion on #spoutdev about the commit strategy and why it is bad to commit untested code to master ;)

Not accusing you - I've just had some pull requests that did not work (or even compile) out of the gate.

**Pull request merged**
