### PR TITLE
AlphaText Fix.

### PR DESCRIPTION
**Pull request by dluechoy**
Tesselator used instead of GL11 - restored chat/text functionality on Intel machines.

Shadows reduced to 70% (of foreground text) opacity. Black text now slightly more readable.

No appreciable peanalty for users not afflicted by white text.

### CODE REVIEW

**Comment by dluechoy** [comment]
I've ported the current version of my White Text Fix, with some additional 'enhancements' for Spout.
I believe this addresses [Spoutcraft Colored text Help!!!](http://forums.spout.org/threads/spoutcraft-colored-text-help.2822/), and [Double text error](http://forums.spout.org/threads/double-text-error.2492/)

Specifically I've tackled text doubling.
The inGameGUI is rendering the string THEN triming it. This is why the the last line fragment is missing from the messages wrapped by the client, it never gets rendered.
This is fixed by pointing to wrapStringToWidth in FontRenderer instead of in InGameGUI

The bukkit stripColor method also strips styling information, making width calculations (and returned strings) incorrect.
This is fixed by handling formatting in FontRenderer instead of in Bukkit.

Distorted glyphs/characters are caused by texture handling elsewhere in the client. This is most apparent in fonts that appear to have one edge cut off, or stretched.
The edge offsets have been changed +0.02units in FontRenderer to try and compensate. Should the shifing be changed again then it will be necessary to readjust this.

Garbage being attached to the end of fullwidth fonts is reduced by making FontUtil character width sensitive while calculating widths (still happens with fonts > 256 px wide), and it stillgets confused by thin characters. (see Fullwidth Unicode and wide characters in Misa413)

The string widths are also being miscalculated by converting between fixed-point, floatingpoint, integer, floating point, integer, floating point then finally back to integer between FontRenderer and Font Utilities.
This is fixed by handling Formatting in floating-point inside FontRenderer.

Colour is fixed by using Tesselator to build a buffer instead of using FontRenderer to call GL11 directly (Also allows future enhancements to Tesselator to benefit FontRenderer too). Calculations are still in Float instead of Double to maintain compatibility with mods-that-may possibly override methods within FontRenderer.

blurring/double vision of bold text is reduced by stretching the second pass half a 'normalized unit' (1 pixel@ normal scale) on Default and Custom fonts, and reducing the offset for Unicode Glyphs to one half 'normalized unit' (1 px @ normal scale). Bold also nolonger exaggerates spaces. (see Unicode)

String width calculations are now aware of the width of spaces (srsly WTF!), what characters are bold (now that bukkit isn't eating the formatting data) and how wide the characters actually are (now that FontUtil isn't constantly rounding off). (see Misa413)

AlphaText Series C - Before and After screenshots:
- Unicode Glyphs:
  - [](https://picasaweb.google.com/lh/photo/S4ho6cGJzMJneN7fxaHdkNvkYeXQ7HSM2-0CtrUnZaI?feat=embedwebsite) [](https://picasaweb.google.com/lh/photo/Ioib1Bi0F_u-LecCC_o0mtvkYeXQ7HSM2-0CtrUnZaI?feat=embedwebsite)
- Default Font:
  - [](https://picasaweb.google.com/lh/photo/Q0ma-q3evDSFFPdOchAY9tvkYeXQ7HSM2-0CtrUnZaI?feat=embedwebsite) [](https://picasaweb.google.com/lh/photo/SfAnfszas2XBLQJzi4mGltvkYeXQ7HSM2-0CtrUnZaI?feat=embedwebsite)
- Custom Font (Fullwidth Unicode):
  - [](https://picasaweb.google.com/lh/photo/yTxgrR9v7fNpk389dP54IdvkYeXQ7HSM2-0CtrUnZaI?feat=embedwebsite) [](https://picasaweb.google.com/lh/photo/-YzXgPEd-wK867g1Uqw4n9vkYeXQ7HSM2-0CtrUnZaI?feat=embedwebsite)
- Custom Font (Misa413):
  - [](https://picasaweb.google.com/lh/photo/UFwtENOspARsmkK56UwQnNvkYeXQ7HSM2-0CtrUnZaI?feat=embedwebsite)  [](https://picasaweb.google.com/lh/photo/6MwownUGMP7SI7_eDbpZ3tvkYeXQ7HSM2-0CtrUnZaI?feat=embedwebsite)

Add this code to chatmanager to test..

``` javascript
            } else if (command.startsWith("/fonttest")) {
                SpoutClient.getHandle().ingameGUI.addChatMessage("\u00a7oSed ut perspiciatis, \u00a70unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, \u00a71totam rem aperiam eaque ipsa, \u00a72quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, \u00a73explicabo. \u00a74\u00a7lNemo enim ipsam voluptatem, \u00a75quia voluptas sit, \u00a76aspernatur aut odit aut fugit, \u00a77sed quia consequuntur magni dolores eos, \u00a78qui ratione voluptatem sequi nesciunt, \u00a79neque porro quisquam est, \u00a7aqui dolorem ipsum, \u00a7bquia dolor sit amet, \u00a7cconsectetur, \u00a7dadipisci[ng] velit, \u00a7esed quia non numquam [do] eius modi tempora inci[di]dunt, \u00a7fut labore et dolore magnam aliquam quaerat voluptatem. \u00a7m\u00a7nUt enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? \u00a7mQuis autem vel eum iure reprehenderit, \u00a7oqui in ea voluptate velit esse, \u00a7lquam nihil molestiae consequatur, \u00a7kvel illum, \u00a7rqui dolorem eum fugiat, quo voluptas nulla pariatur?");
            }
```

I am aware that I have broken much optimization, and have not used stringbuilder correctly. Any enhancements are welcome.

**Comment by RoyAwesome** [comment]
some procedural things:

You need to squash your commits down to one
You need to sign-off your commits.  This means you agree to our code license.  You can do this with the -s flag when committing.

Here are our pull request guidelines:  http://forums.spout.org/threads/pull-request-guidelines.2922/

**Comment by dluechoy** [comment]
Git is being a git about rolling back "rebase -i HEAD~#" because there already is a pullrequest.
Similarly SmartGit is being even dumber by adding another commit when asked to rebase HEAD to.

Did sign off though.

edit: 
would be nice if the readme.md reflected that thread.

**Comment by Afforess** [comment]
Merged manually http://spout.in/2bf0fa5

**Pull request closed without merging**
