### PR TITLE
HTTP proxy support for multiplayer connections

### PR DESCRIPTION
**Pull request by timatooth**
I created this issue SPOUTCRAFTLAUNCHER-12 ages ago. Afforess added proxy parameters for the launcher which was awesome but they don't work for spoutcraft socket connections like polling or connecting to mc servers. This is the only solution I could think of: use a proxy settings configuration file.

I meant to make this one commit but forgot to add two files.

### CODE REVIEW

**Comment by Afforess** [comment]
We can pass the launcher arguments onto the Spoutcraft game instead of a config file. We already do this for portable mode.

**Comment by timatooth** [comment]
How would that happen. And I think it would be better to store settings in a configuration somewhere because launcher parameters are a pain.

**Comment by lukespragg** [comment]
You can easily make a shortcut for the launcher to pass parameters to it, even add an icon.

**Comment by timatooth** [comment]
Or it can be easily be included in the launcher so normal people who are not aware of parameters, CLI, batch/shell scripting can supply them in the launcher. Which do you think sounds better?

**Comment by lukespragg** [comment]
They'll be just as aware of the parameters as a file hidden in some folder, except most already know about the parameters if they've ever used any of the other ones.

Also, your formatting doesn't match our conventions.

**Comment by timatooth** [comment]
Ok I'll try fix the formatting and figure out another way to get the parameters from the launcher to spoutcraft.

**Comment by lukespragg** [comment]
Also, why not implement a "Proxy Settings" GUI sub-page under Options for changing the file? :P

**Comment by timatooth** [comment]
I have for the launcher if that's what you mean :) http://i45.tinypic.com/x6alc3.png but Afforess wasn't keen on adding more options to the launcher :(

**Comment by lukespragg** [comment]
Yeah... we removed the advanced options for a reason.

**Comment by timatooth** [comment]
Not a very good reason I believe. To hide features from users so they don't cause you more headaches for debugging I presume. I know 5 people that want to play but cannot because of the decision you have endeavored for benefits of yourselves only, not the people that want to legitimately play but are behind a proxy/firewall and there are a _lot_ of people in this situation. There can and should be an option somewhere to do this!

**Comment by lukespragg** [comment]
The options menu was removed, as users were setting options to utilize older builds, and repeatedly reporting old bugs that had already been fixed, resulting in time lost for us and headache for the end-user. Most of the time, users will not need to access the command-line options unless for development or debugging purposes. That is the reason they were moved, and a perfectly good one. If we were to add a "Proxy" button, I am sure we'll have issues with users changing settings in it and making it break their launcher. The majority of our userbase is young, and may not even know what a proxy is.

I have seen perhaps... 3 or 4 people that want to proxy their connection with Spoutcraft, that doesn't really seem like a lot of people. Making things more confusing for the vast majority vs leaving it as an advanced command-line option for those who actually need it sounds like a better idea.

**Comment by timatooth** [comment]
That kind of philosophy sucks I reckon. But I understand what you mean.  Anyway the formatting you meant was the spaces right? I _really_ want this fixed lol.

**Comment by lukespragg** [comment]
Yup, it's not the best option, but it makes things easier for the majority. Our formatting conventions are listed on the readme and on http://spout.in/prguide. Essentially, you should be using tabs, not spaces, in-line curly braces with spaces padding them inside such as } else {, etc.

**Pull request closed without merging**
