### PR TITLE
Text alpha

### PR DESCRIPTION
**Pull request by dluechoy**
Allow players to switch to RGB colour space for text rendering. This allows players affected by the white text bug to trade transparancy for colour.

### CODE REVIEW

**Comment by dluechoy** [comment]
Three of those commits is fixing one string.

I did not know why Smart Git threw a tantrum when I tried to ammend it, and I probabaly won't waste any more time jumping through hoops to dismiss the error messages Smart Git and Git-bash are shitting out.

(edit:) Because I made the pull request before noticing that the string had that garbage at the end of it appending the commits did not work to preserve the integrity of the previous pull request. However additional commits were appended to the pull request just fine. Even after hours of BS to get the rebase to happen, it was rolled back by GIT even with the previous pull request open/shut. And there does not appear to be a means of force updating the commit range to the squished and/or merged commits. And the previous pull requests are inhibiting fixing this anyways.

So, If having it as four commits is such a big fucking deal, leave a comment and I'll refork this.

**Comment by Afforess** [comment]
Looks good, I can manually squash the commits, it's not that big of a deal. I'll test it tonight.

**Comment by dluechoy** [comment]
Meow. ^ ^

**Comment by dluechoy** [comment]
Obsoleted.

**Pull request closed without merging**
