### PR TITLE
Implemented gravity multiplier

### PR DESCRIPTION
**Pull request by AlinaNova21**
I implemented setGravityMultiplier and getGravityMultiplier

### CODE REVIEW

**Comment by narrowtux** [comment]
Can you make sure you use tabs and do formatting right so it aligns nicely with the other methods?
Also, when you make it in LivingEntity, why not let all LivingEntities profit from this, not just the player?

**Comment by AlinaNova21** [comment]
I am planning on doing more to this, My plans are currently to add and implement all the methods from livingEntity. Then I may work on others. Formatting looked right when I saved.. I may have used spaces instead of tabs though... Used to yaml...

**Comment by narrowtux** [comment]
I'd rather suggest to make it for all the entities :) So I could make floating items in the air. 
If you use eclipse, select all and then press ctrl-I or CMD-I to indent nicely.

**Comment by narrowtux** [comment]
Oh, wrong number :P
I meant #58

**Pull request closed without merging**
