### PR TITLE
Custom character width detection fix.

### PR DESCRIPTION
**Pull request by dluechoy**
Uses Alpha instead of Green channel to determine opacity in a custom font texture, allowing characer widths to be determined correctly.

Also trims most of the 'garbage' off of fullwidth characters, though with large font textures (1024^2) a single column of garbage pixels will remain.

Changed 'colIdx' back from 'pixel' to maintain consistency with pclewis/mcpatcher.

Signed-off-by: dluechoy dluechoy@gmail.com

### CODE REVIEW

**Comment by LunNova** [comment]
@dluechoy 

Squash these commits.

`git rebase -i HEAD~3`
`Change the last commit line's "pick" to "f"`
`git push --force`

**Comment by dluechoy** [comment]
Somehow that did not reduce the number of commits.

**Comment by LunNova** [comment]
Erm... strange?

`git rebase -i HEAD~2`
`Remove the allow bindings for mouse clicks commit line`
`git push --force`

**Comment by dluechoy** [comment]
That's better.

**Pull request merged**
