### PR TITLE
Removed un-usefull commits

### PR DESCRIPTION
**Pull request by duckdoom5**
Signed-off-by: duckdoom5 j_e_l_l_e@hotmail.com

### CODE REVIEW

**Comment by thedudeguy** [comment]
duckdoom5 can you elaborate on this PR?

**Comment by Doridian** [comment]
In his previous PR that was accepted he had useless stuff (that caused bugs). This PR removes it again.

**Comment by thedudeguy** [comment]
looks like it has potential to be useful, though :P.

**Comment by duckdoom5** [comment]
@thedudeguy: @Afforess said about the mouse click call :"Pretty sure this stuff is not needed, and is wasting network bandwidth."

I tested if it worked and it did, but there was still a bug where you can click right-ctrl to fire it. But you fixed that/broke my "fix" with your commit.

so I removed it.

**Comment by thedudeguy** [comment]
oh ok. In my testing I was never receiving mouse click events in SpoutPlugin anyway. I think if you really wanted mouse click events, it would be better to create a new Packet Class MouseClickedPacket or something.

**Comment by duckdoom5** [comment]
hmm, ok I will do it tommorow.

**Pull request merged**
