### PR TITLE
Possibly fixed Keyboard.MOUSE_* not being fired correctly

### PR DESCRIPTION
**Pull request by duckdoom5**
this should fix it, I've also added a sprinting fix so you don't keep sprinting when your hunger is less than 6 (that's 3 full meat sticks :P)

### CODE REVIEW

**Comment by lukespragg** [comment]
This is actually using an old source location. You'll have to redo it.

**Comment by Afforess** [comment]
> This is actually using an old source location. You'll have to redo it.

Doesn't seem like too much code - could just have @narrowtux or @Znickq look at it and manually merge.

**Comment by ZNickq** [comment]
What does this fix exactly? :P
I mean i get the code, but i'm not sure why we need that handling...

**Comment by duckdoom5** [comment]
When you use Keyboard.Mouse\* it doesn't get launched, when clicking a mouse button. I created this pull to launch the Keyboard.Mouse_\* value when actually pressing the mouse button.

to show what I mean here is a simple code:

@EventHandler
public void onKeyPressedEvent(KeyPressedEvent event) {
    Keyboard key = event.getKey();
    SpoutPlayer splayer = event.getPlayer();
    if(key.equals(Keyboard.MOUSE_RIGHT)){
        splayer.sendMessage("right-click");
    }
}

this code gets launched when you press right-ctrl instead of right mouse button

**Comment by ZNickq** [comment]
kk, i'll merge it soon :)

**Comment by duckdoom5** [comment]
added to latest commit (sorry, won't happen again)

**Pull request closed without merging**
