### PR TITLE
Reduced TextField traffic

### PR DESCRIPTION
**Pull request by Dantoes**
By creating a thread that waits a little time for the next input, the traffic caused by TextFields can be dramatically reduced. Until now the formula for the TextField traffic is (where 95 is the static overhead and n the amount of characters typed in):

formula

Typing a text of 150 characters causes 36900 bytes of traffic over time. The new methods only sends the updated contents to the server if 500ms (625ms worst case) have passed since the last keyboard input. If the user types the same text non-stop, only 395 bytes are sent with the new method.

I also removed a method of GuiScreen, which seemed to be unnecessary (please check):
knowbuddy/Spoutcraft@77791fe3dbccfcdb172ff58cf673de8924369053

### CODE REVIEW

**Comment by Dantoes** [comment]
Uh, because @Top-Cat manually merged my last pull request, this pull request includes commits which shouldn't be part of it. Is there something I can do about that?

**Comment by narrowtux** [comment]
@knowbuddy, why did you remove onKeybordTyped?

**Comment by Dantoes** [comment]
@narrowtux, it has been replaced by [handleKeyboardInput](https://github.com/SpoutDev/Spoutcraft/blob/master/src/minecraft/net/minecraft/src/GuiScreen.java#L214)

Due to Eclipse's call-search, onKeybordTyped is never called.

**Comment by Dantoes** [comment]
I found a bug: when closing the Screen before the thread sends the TextField content to the server and the server-side plug-in listens for a ScreenCloseEvent to get the text, the text will have the content of the last update (if any).

This can be solved by calling GuiScreen::onGuiClosed before sending a screen event to the server in [Minecraft::displayGuiScreen](https://github.com/SpoutDev/Spoutcraft/blob/master/src/minecraft/net/minecraft/client/Minecraft.java#L489). In this case it would be possible to terminate the running threads and enforce the sending of all TextField contents.

But before I solve this issue I'd like to know if you think the whole delayed send thing makes sense :)

**Comment by narrowtux** [comment]
I merged it manually.

**Pull request merged**
