### PR TITLE
Screenshot grabbing - grab screenshot from client

### PR DESCRIPTION
**Pull request by angelsl**
- Adds ScreenShotHelper from Minecraft (to add in a method and it up a bit).
- PacketScreenshot (47)

### CODE REVIEW

**Comment by Top-Cat** [comment]
Does this work with large screens where sending it as a packet could be an issue?

**Comment by angelsl** [comment]
How large of a screen? I've only tested it on localhost.. and also, the screenshots are transmitted as PNG, and if the client can get the world, it should be able to send whatever image file results.

**Comment by angelsl** [comment]
A screenshot of MC at 1600x900 fullscreen I took is 270kb, I think it should be fine..

**Comment by Top-Cat** [comment]
Depends on the content, screenshots in my .spoutcraft/screenshots folder range from 2.14MB at 1680x1028 (which is bad) to 133kb at 854x480 (which would be fine)

**Comment by angelsl** [comment]
What resolution are you running at? Anyway, maybe the SS could be resized clientside before sending.. hmm

**Comment by Top-Cat** [comment]
I edited, the largest is 1680x1028, but some at that size are only 430kb

**Pull request merged**
