### PR TITLE
Fixed drawTexture when left >= 0 and top >= 0

### PR DESCRIPTION
**Pull request by mityada**
This makes possible to use GenericTexture for rendering a slice of the texture.

### CODE REVIEW

**Comment by Rycochet** [comment]
Doh - and that's why I don't get on with gl code...

**Comment by Afforess** [comment]
We are changing licenses. Do you agree with distribute this under our newer license? https://github.com/SpoutDev/Spout/blob/master/LICENSE.txt

**Comment by mityada** [comment]
Yes, I agree.

**Comment by Afforess** [comment]
Merged manually, thanks!

**Comment by docteurzoidberg** [comment]
Great ! :D

**Comment by mityada** [comment]
https://github.com/SpoutDev/Spoutcraft/commit/690b76cee2ecb03f57ac3c85340b089b8d6d7763
After that commit textures are rendering upside down...

**Comment by Afforess** [comment]
This pull request does not work perfectly, it wrecks the full image in the server list. Please correct. I have reverted it.

**Pull request closed without merging**
