### PR TITLE
Modified Item Tooltips RE *Fixed*

### PR DESCRIPTION
**Pull request by masp**
This is just a pull request that fixes the previous request, because the other repository was screwed up and was messing with my sanity. I'm really sorry if this is improper to do but for the life of me for some reason the old repo wasn't cooperating with me at all.

### CODE REVIEW

**Comment by lukespragg** [comment]
Why did you change //Spout Start to //Spout Start Edited End?

**Comment by masp** [comment]
I did that because my commit change for comments included another //Spout start so I decided to add the Edited note to avoid confusion on where it originally began and where it's new end is.

**Comment by narrowtux** [comment]
@masp that's not neccessary. We use //Spout Start and //Spout End annotations to see where we modified Vanilla MC Code, so we can merge new versions easier.

**Comment by masp** [comment]
Oh, I'm sorry. I just thought I might as well clarify it. Should I change it?

**Comment by Afforess** [comment]
> Should I change it? 

Yes please.

**Pull request merged**
