### PR TITLE
Update src/main/java/org/spoutcraft/client/chunkcache/ChunkNetCache.java

### PR DESCRIPTION
**Pull request by Doridian**
Fixes NPE on the Server!

### CODE REVIEW

**Comment by Zidane** [comment]
We would probably pull this @Doridian but we have to have you sign it off.

**Comment by ZNickq** [comment]
Merged manually, thanks :D

**Comment by Raphfrk** [comment]
Thanks.  It is crazy that the server explodes if you send a zero length array.

**Comment by Doridian** [comment]
Ye, someone over at Mojang thought if you send a zero length array it would be neat to make p250.data = null and not byte[0]. Pff.

**Pull request closed without merging**
